version: '3.3'

services:
  logspout:
    build:
      context: extensions/logspout
      labels:
        group: "deviantony/docker-elk"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:4990
      LOGSTASH_TAGS: docker-elk
    networks:
      - elk
    depends_on:
      - logstash
    restart: on-failure
